// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_qwY-HtEIE7VJ9VDQs7NdS79Aff92xdI',
    appId: '1:656378444249:android:b0d120cec88071eede01c8',
    messagingSenderId: '656378444249',
    projectId: 'moneymemo-b6770',
    storageBucket: 'moneymemo-b6770.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeuQUuLf_WZUlH0u8EXMGrSpr2z_fOm8Q',
    appId: '1:656378444249:ios:10edaa83f1e55dcfde01c8',
    messagingSenderId: '656378444249',
    projectId: 'moneymemo-b6770',
    storageBucket: 'moneymemo-b6770.firebasestorage.app',
    iosBundleId: 'com.example.moneymemo2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7JOa9A4qz_REMOO5xTNqGXkPXmVCse2Q',
    appId: '1:656378444249:web:3c8bbb50ad3040fede01c8',
    messagingSenderId: '656378444249',
    projectId: 'moneymemo-b6770',
    authDomain: 'moneymemo-b6770.firebaseapp.com',
    storageBucket: 'moneymemo-b6770.firebasestorage.app',
    measurementId: 'G-BTSFGZCSHH',
  );
}
